# Generated by Django 4.1.3 on 2022-11-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'avançado'), ('B', 'básico'), ('I', 'intermediário')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'Noturno'), ('V', 'Vespertino'), ('M', 'Matutino')], default='M', max_length=1),
        ),
    ]
