# Generated by Django 4.1.3 on 2022-11-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_curso_nivel_alter_matricula_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('A', 'avançado'), ('I', 'intermediário'), ('B', 'básico')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('N', 'Noturno'), ('M', 'Matutino'), ('V', 'Vespertino')], default='M', max_length=1),
        ),
    ]
